"""
Quiz source — AI tools awareness question bank.
Questions divided into 3 stages by difficulty/progression.
Stage 1: Foundation  — widely-known tools and basic concepts
Stage 2: Applied     — platform and ecosystem knowledge
Stage 3: Advanced    — frameworks, open-source, agents, internals

Seeding: SHA-256(date_str:stage:<n>) gives cryptographically independent daily seeds.
No two dates or stages share correlated seeds — eliminates the clustering problem
seen with sequential integer seeds.
"""

import hashlib
import random
from datetime import date as _date


def _qid(text: str) -> str:
    return hashlib.md5(text.encode()).hexdigest()[:12]


def _daily_seed(date_str: str, stage: int) -> int:
    """
    SHA-256 of '{date_str}:stage:{stage}' → uniform 31-bit seed.
    Each (date, stage) pair is cryptographically independent —
    no sequential correlation between consecutive days or adjacent stages.
    """
    key = f"{date_str}:stage:{stage}".encode()
    return int(hashlib.sha256(key).hexdigest(), 16) % (2 ** 31)


QUESTION_BANK: list[dict] = [

    # ── Stage 1: Foundation ────────────────────────────────────────────────────

    {
        "question": "Which company developed the Claude AI assistant?",
        "option_a": "OpenAI",
        "option_b": "Google",
        "option_c": "Anthropic",
        "option_d": "Meta",
        "correct": "c",
        "explanation": "Claude is developed by Anthropic, an AI safety company founded in 2021 by former OpenAI researchers including Dario and Daniela Amodei.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "GitHub Copilot is primarily used as a tool for?",
        "option_a": "Generating images from text prompts",
        "option_b": "AI-powered code completion and generation",
        "option_c": "Video editing with AI",
        "option_d": "Translating documents automatically",
        "correct": "b",
        "explanation": "GitHub Copilot is an AI pair programmer that suggests code completions and generates entire functions, powered by OpenAI Codex and later GPT-4.",
        "category": "coding",
        "stage": 1,
    },
    {
        "question": "Midjourney is best described as a tool for?",
        "option_a": "AI-generated images from text descriptions",
        "option_b": "Writing long-form articles automatically",
        "option_c": "Transcribing audio to text",
        "option_d": "Automating spreadsheet tasks",
        "correct": "a",
        "explanation": "Midjourney is a generative AI image tool that creates high-quality artwork and photorealistic visuals from natural language text prompts.",
        "category": "image-generation",
        "stage": 1,
    },
    {
        "question": "Which AI tool is best known for web search with real-time cited answers?",
        "option_a": "Claude",
        "option_b": "Perplexity AI",
        "option_c": "Stable Diffusion",
        "option_d": "ElevenLabs",
        "correct": "b",
        "explanation": "Perplexity AI is an AI-powered search engine that delivers direct answers with cited web sources, combining LLM capabilities with real-time search.",
        "category": "ai-search",
        "stage": 1,
    },
    {
        "question": "DALL-E is an AI image generation model created by?",
        "option_a": "Google",
        "option_b": "Stability AI",
        "option_c": "Microsoft",
        "option_d": "OpenAI",
        "correct": "d",
        "explanation": "DALL-E is developed by OpenAI. DALL-E 3 is integrated into ChatGPT and is one of the leading text-to-image generation models.",
        "category": "image-generation",
        "stage": 1,
    },
    {
        "question": "What kind of tool is Cursor?",
        "option_a": "A video generation platform",
        "option_b": "An AI-enhanced code editor",
        "option_c": "A voice cloning tool",
        "option_d": "An email automation assistant",
        "correct": "b",
        "explanation": "Cursor is an AI-first code editor built on VS Code that integrates chat, code generation, and intelligent editing directly into the development environment.",
        "category": "coding",
        "stage": 1,
    },
    {
        "question": "Google's AI assistant was renamed from Bard to which name in February 2024?",
        "option_a": "LaMDA",
        "option_b": "Vertex AI",
        "option_c": "Gemini",
        "option_d": "Duet AI",
        "correct": "c",
        "explanation": "Google renamed its AI assistant from Bard to Gemini in February 2024, aligning it with the underlying Gemini family of multimodal AI models.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "ChatGPT was developed and launched by which company in November 2022?",
        "option_a": "Google",
        "option_b": "Microsoft",
        "option_c": "OpenAI",
        "option_d": "Anthropic",
        "correct": "c",
        "explanation": "ChatGPT was launched by OpenAI in November 2022 and became the fastest-growing consumer application in history, reaching 100 million users in just two months.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "What does 'AI hallucination' mean?",
        "option_a": "The AI generates visual illusions in images",
        "option_b": "The AI confidently produces false or invented information",
        "option_c": "The AI runs too slowly due to overloading",
        "option_d": "The AI refuses to answer a question",
        "correct": "b",
        "explanation": "AI hallucination refers to when a language model generates plausible-sounding but factually incorrect or invented information — a key limitation to be aware of when using AI tools.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "Canva's suite of AI-powered design features is collectively called?",
        "option_a": "Canva AI+",
        "option_b": "Design Intelligence",
        "option_c": "Magic Studio",
        "option_d": "Smart Canvas",
        "correct": "c",
        "explanation": "Canva's Magic Studio bundles AI tools including Magic Write (text), Magic Media (image/video generation), Magic Eraser, and Magic Edit into one integrated creative suite.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Notion AI is an AI assistant built into which productivity workspace?",
        "option_a": "Microsoft OneNote",
        "option_b": "Notion",
        "option_c": "Confluence",
        "option_d": "Evernote",
        "correct": "b",
        "explanation": "Notion AI is natively integrated into Notion's workspace, helping users write, summarise, translate, and brainstorm without leaving their notes and documents.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Grammarly uses AI primarily to assist with?",
        "option_a": "Generating code in multiple languages",
        "option_b": "Creating AI-generated images",
        "option_c": "Writing assistance — grammar, clarity, and tone",
        "option_d": "Translating spoken audio in real time",
        "correct": "c",
        "explanation": "Grammarly is an AI writing assistant that checks grammar, improves clarity, adjusts tone, and now includes generative AI features for drafting and rewriting text.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "What makes GPT-4 'multimodal' compared to earlier GPT models?",
        "option_a": "It can run on multiple devices simultaneously",
        "option_b": "It supports multiple programming languages",
        "option_c": "It can process both text and images as input",
        "option_d": "It has multiple response styles to choose from",
        "correct": "c",
        "explanation": "GPT-4's multimodal capability means it accepts images as well as text as input, allowing it to analyse photos, charts, and documents — not just written prompts.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "OpenAI's Sora model is capable of?",
        "option_a": "Translating speech between 100 languages",
        "option_b": "Generating realistic video from text descriptions",
        "option_c": "Creating 3D models from photos",
        "option_d": "Automating browser tasks with AI agents",
        "correct": "b",
        "explanation": "Sora is OpenAI's text-to-video model that can generate high-quality, realistic videos up to one minute long from a written prompt.",
        "category": "video-generation",
        "stage": 1,
    },
    {
        "question": "What does 'LLM' stand for in AI?",
        "option_a": "Low-Latency Machine",
        "option_b": "Large Language Model",
        "option_c": "Layered Learning Module",
        "option_d": "Linear Logic Matrix",
        "correct": "b",
        "explanation": "LLM stands for Large Language Model — a type of AI trained on vast text data to understand and generate human language. GPT-4, Claude, and Gemini are all LLMs.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "'GPT' in ChatGPT and GPT-4 stands for?",
        "option_a": "General Purpose Technology",
        "option_b": "Graphical Processing Transformer",
        "option_c": "Generative Pre-trained Transformer",
        "option_d": "Global Predictive Text",
        "correct": "c",
        "explanation": "GPT stands for Generative Pre-trained Transformer — the neural network architecture underlying OpenAI's language models, trained on large text corpora before being fine-tuned for conversation.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "Microsoft's AI assistant integrated into Bing search and Windows is called?",
        "option_a": "Cortana AI",
        "option_b": "Azure Assistant",
        "option_c": "Copilot",
        "option_d": "Bing Intelligence",
        "correct": "c",
        "explanation": "Microsoft rebranded its AI-powered Bing search assistant to Copilot, now available across Windows 11, Edge browser, and Microsoft 365 — powered by GPT-4.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "In AI, a 'prompt' refers to?",
        "option_a": "A warning message when AI makes an error",
        "option_b": "The input text or instruction you give to an AI model",
        "option_c": "The AI model's internal training memory",
        "option_d": "A type of neural network layer",
        "correct": "b",
        "explanation": "A prompt is the text input you provide to an AI model to guide its response. Writing effective prompts — known as prompt engineering — has become a key skill for getting the best results from AI tools.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "Otter.ai is primarily used for?",
        "option_a": "Generating AI-written research papers",
        "option_b": "Creating AI-powered video presentations",
        "option_c": "Automated meeting transcription and note-taking",
        "option_d": "AI-powered customer service chatbots",
        "correct": "c",
        "explanation": "Otter.ai records, transcribes, and summarises meetings in real time, integrating with Zoom, Google Meet, and Microsoft Teams to automatically capture key discussion points and action items.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Synthesia is an AI platform known for?",
        "option_a": "Synthesising music from text prompts",
        "option_b": "Creating AI-generated videos using digital human avatars",
        "option_c": "Generating photorealistic images from text descriptions",
        "option_d": "Voice cloning for podcast production",
        "correct": "b",
        "explanation": "Synthesia lets you create professional videos by typing a script — an AI avatar delivers it on screen. It is widely used for corporate training, product demos, and explainer videos without cameras or studios.",
        "category": "video-generation",
        "stage": 1,
    },
    {
        "question": "Apple's on-device AI system, integrated into iPhone and Mac, is called?",
        "option_a": "Siri Pro",
        "option_b": "Apple AI",
        "option_c": "Apple Intelligence",
        "option_d": "CoreAI",
        "correct": "c",
        "explanation": "Apple Intelligence was announced in 2024, bringing on-device AI features to iPhone 15 Pro and newer devices — including writing tools, smart photo editing, image generation, and an enhanced Siri.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Character.AI is best known for allowing users to?",
        "option_a": "Generate professional marketing content with AI",
        "option_b": "Build custom AI chatbot workflows for businesses",
        "option_c": "Chat with AI characters and personas, including fictional ones",
        "option_d": "Create AI-generated short films",
        "correct": "c",
        "explanation": "Character.AI lets users create and converse with AI characters — from celebrities to fictional characters to custom personas — and became one of the fastest-growing AI consumer apps after launch.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "What is a 'context window' in a large language model?",
        "option_a": "The graphical user interface of an AI chatbot",
        "option_b": "The maximum amount of text an LLM can process in one interaction",
        "option_c": "The browser window used to access AI tools online",
        "option_d": "A privacy setting that limits AI data collection",
        "correct": "b",
        "explanation": "The context window defines how much text — conversation history, documents, and instructions — an LLM can 'see' at once. Larger context windows (e.g. 1 million tokens) mean the AI can process entire books in one request.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "HeyGen is an AI tool used primarily for?",
        "option_a": "Generating background music for videos",
        "option_b": "AI-powered video generation and avatar dubbing",
        "option_c": "Creating AI-written screenplays",
        "option_d": "Automating social media posting schedules",
        "correct": "b",
        "explanation": "HeyGen generates talking avatar videos from text scripts and is widely used for AI-powered video translation — dubbing content into other languages while matching lip movements using AI.",
        "category": "video-generation",
        "stage": 1,
    },
    {
        "question": "Slack AI helps team members primarily by?",
        "option_a": "Automatically scheduling meetings and calendar events",
        "option_b": "Generating code snippets directly in Slack channels",
        "option_c": "Summarising conversations, threads, and channels",
        "option_d": "Translating Slack messages into different languages in real time",
        "correct": "c",
        "explanation": "Slack AI summarises long threads and channels so you can catch up on missed conversations quickly — it also answers questions based on your workspace's message history.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Google's Gemma models are best described as?",
        "option_a": "Google's consumer chatbot competing with ChatGPT",
        "option_b": "Lightweight, open-source AI models designed for local deployment",
        "option_c": "Google's proprietary enterprise AI platform",
        "option_d": "AI-powered search ranking algorithms",
        "correct": "b",
        "explanation": "Gemma is Google's family of open-source, lightweight language models designed to run efficiently on laptops and edge devices — making advanced AI accessible without cloud infrastructure.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "OpenAI's o1 and o3 model series are specialised for?",
        "option_a": "Generating photorealistic images from text",
        "option_b": "Real-time voice conversation with emotional awareness",
        "option_c": "Advanced reasoning, mathematics, and complex problem-solving",
        "option_d": "Creating long-form video content from prompts",
        "correct": "c",
        "explanation": "OpenAI's o-series models use extended 'chain-of-thought' reasoning, taking extra time to think through problems before answering — significantly outperforming standard GPT-4 on math, coding, and scientific tasks.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "A 'foundation model' in AI refers to?",
        "option_a": "A basic AI model with very limited capabilities",
        "option_b": "The first AI model ever created by a company",
        "option_c": "A large model pre-trained on broad data that can be adapted to many tasks",
        "option_d": "A government-certified AI system meeting safety standards",
        "correct": "c",
        "explanation": "Foundation models like GPT-4, Claude, and Gemini are trained on massive datasets to develop general capabilities, then fine-tuned or prompted for specific tasks — forming the 'foundation' of modern AI applications.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "Microsoft Designer is an AI tool primarily used for?",
        "option_a": "Writing and editing code in Visual Studio",
        "option_b": "AI-powered graphic design and image creation",
        "option_c": "Designing database schemas with AI assistance",
        "option_d": "Creating AI-generated 3D architectural models",
        "correct": "b",
        "explanation": "Microsoft Designer uses AI (powered by DALL-E) to help users create social media graphics, presentations, invitations, and marketing visuals — integrated into Microsoft 365's creative tools.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "At a basic level, an 'AI agent' is?",
        "option_a": "A human expert who reviews and approves AI outputs",
        "option_b": "An AI system that can take actions and complete multi-step tasks autonomously",
        "option_c": "A software plug-in that connects apps to AI APIs",
        "option_d": "A chatbot that responds to simple customer queries",
        "correct": "b",
        "explanation": "An AI agent goes beyond simple Q&A — it can plan, use tools (web search, code execution, APIs), and complete complex tasks across multiple steps without requiring human input at each stage.",
        "category": "agent-frameworks",
        "stage": 1,
    },
    {
        "question": "What does 'AI bias' refer to?",
        "option_a": "The tendency of AI to favour faster responses over accuracy",
        "option_b": "Systematic errors in AI outputs caused by skewed training data or design",
        "option_c": "The preference AI has for longer, more detailed prompts",
        "option_d": "The processing delay between a question and an AI response",
        "correct": "b",
        "explanation": "AI bias occurs when a model produces unfair or skewed outputs — often because training data reflects historical inequalities or the design process lacked diverse perspectives. It is a key area of AI ethics research.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "What is the purpose of a 'system prompt' in AI chatbots?",
        "option_a": "To restart the AI conversation from the beginning",
        "option_b": "To set the AI's behaviour, persona, and rules before the conversation starts",
        "option_c": "To send urgent messages that get prioritised by the AI",
        "option_d": "To check if the AI server is running correctly",
        "correct": "b",
        "explanation": "A system prompt is a set of instructions given to the AI before the user conversation begins — defining its role, tone, restrictions, and personality. It is how products like customer service bots and specialised AI tools are customised.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "Luma Dream Machine is an AI tool used for?",
        "option_a": "Generating dream-like visual art from image references",
        "option_b": "AI-powered text-to-video generation",
        "option_c": "Creating 3D environments from 2D photographs",
        "option_d": "Generating music and soundscapes from text descriptions",
        "correct": "b",
        "explanation": "Luma Dream Machine generates short, high-quality videos from text prompts or images, competing in the text-to-video space alongside OpenAI Sora and Runway Gen-3.",
        "category": "video-generation",
        "stage": 1,
    },
    {
        "question": "Zoom AI Companion helps meeting participants by?",
        "option_a": "Automatically joining meetings on your behalf when you are busy",
        "option_b": "Translating all spoken audio into 50 languages in real time",
        "option_c": "Generating meeting summaries, action items, and answering catch-up questions",
        "option_d": "Creating AI-generated slide decks from meeting content",
        "correct": "c",
        "explanation": "Zoom AI Companion summarises meetings, captures action items, and answers questions like 'What did I miss?' — built directly into Zoom at no additional subscription cost for eligible plans.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "'Multimodal AI' refers to an AI system that can?",
        "option_a": "Process instructions in multiple languages simultaneously",
        "option_b": "Run on multiple devices — laptop, phone, and cloud — at the same time",
        "option_c": "Handle multiple types of input — text, images, audio, and video",
        "option_d": "Generate multiple variations of the same output for comparison",
        "correct": "c",
        "explanation": "Multimodal AI models like GPT-4o and Gemini Ultra can process text, images, audio, and video together — enabling richer interactions and more complex tasks than text-only models.",
        "category": "text-generation",
        "stage": 1,
    },

    # ── Stage 2: Applied ───────────────────────────────────────────────────────

    {
        "question": "ElevenLabs is primarily known for which AI capability?",
        "option_a": "Generating 3D models from text",
        "option_b": "AI voice synthesis and voice cloning",
        "option_c": "Real-time language translation",
        "option_d": "AI-powered financial forecasting",
        "correct": "b",
        "explanation": "ElevenLabs specializes in AI voice technology — it can clone voices and generate natural-sounding speech in multiple languages.",
        "category": "voice-audio",
        "stage": 2,
    },
    {
        "question": "What is Hugging Face primarily known as in the AI ecosystem?",
        "option_a": "An open-source ML model hub and community platform",
        "option_b": "A cloud GPU rental service",
        "option_c": "An AI hardware manufacturer",
        "option_d": "A proprietary LLM provider",
        "correct": "a",
        "explanation": "Hugging Face is the leading open-source AI platform hosting thousands of models, datasets, and demo Spaces, and maintains the widely used Transformers library.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "OpenAI's Whisper model is specialised for which task?",
        "option_a": "Speech recognition and audio transcription",
        "option_b": "Image generation from text",
        "option_c": "Music composition",
        "option_d": "Video subtitle generation",
        "correct": "a",
        "explanation": "Whisper is OpenAI's open-source automatic speech recognition system that transcribes and translates audio in dozens of languages with high accuracy.",
        "category": "voice-audio",
        "stage": 2,
    },
    {
        "question": "What is Meta's flagship open-source large language model family called?",
        "option_a": "Falcon",
        "option_b": "LLaMA",
        "option_c": "Mixtral",
        "option_d": "Phi",
        "correct": "b",
        "explanation": "LLaMA (Large Language Model Meta AI) is Meta's family of open-source foundation models. LLaMA 3 is widely used for research, fine-tuning, and local deployment.",
        "category": "text-generation",
        "stage": 2,
    },
    {
        "question": "Microsoft Copilot is deeply integrated into which platform?",
        "option_a": "Google Workspace",
        "option_b": "Salesforce CRM",
        "option_c": "Microsoft 365 (Word, Excel, Teams, Outlook)",
        "option_d": "Adobe Creative Cloud",
        "correct": "c",
        "explanation": "Microsoft Copilot is embedded across Microsoft 365 apps helping users draft documents, analyze data in Excel, summarise Teams meetings, and compose emails in Outlook.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Runway is an AI tool primarily used for?",
        "option_a": "Writing marketing copy",
        "option_b": "AI video generation and editing",
        "option_c": "Generating 3D architectural designs",
        "option_d": "Automating customer support",
        "correct": "b",
        "explanation": "Runway is an AI creative suite known for its Gen-2 and Gen-3 text-to-video models, widely used by filmmakers and creators for AI-assisted video production.",
        "category": "video-generation",
        "stage": 2,
    },
    {
        "question": "NotebookLM, developed by Google, is best used for?",
        "option_a": "Writing code using AI",
        "option_b": "Chatting with and summarising your own documents",
        "option_c": "Generating realistic human faces",
        "option_d": "Automating social media posts",
        "correct": "b",
        "explanation": "NotebookLM lets you upload your own documents and ask questions grounded in them, generating summaries and insights from your specific sources.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Amazon Bedrock is best described as?",
        "option_a": "Amazon's in-house AI assistant for shopping",
        "option_b": "A managed AWS service for accessing multiple foundation models via API",
        "option_c": "A cloud GPU cluster for training custom AI models",
        "option_d": "Amazon's AI-powered logistics optimisation platform",
        "correct": "b",
        "explanation": "Amazon Bedrock is a fully managed AWS service providing access to foundation models from Anthropic (Claude), Meta, Mistral, and others through a single API without managing infrastructure.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Jasper AI is primarily used by businesses for?",
        "option_a": "Automating software testing",
        "option_b": "AI-generated marketing and sales content",
        "option_c": "Real-time financial data analysis",
        "option_d": "Managing cloud infrastructure costs",
        "correct": "b",
        "explanation": "Jasper is an AI content platform built for marketing teams, helping generate blog posts, ad copy, social media content, and brand-aligned text at scale.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Cohere is an AI company focused primarily on?",
        "option_a": "Consumer chatbot applications",
        "option_b": "AI-powered video and image editing",
        "option_c": "Enterprise NLP — embeddings, text generation, and search APIs",
        "option_d": "Autonomous vehicle AI systems",
        "correct": "c",
        "explanation": "Cohere provides enterprise-grade NLP APIs for text generation, classification, and semantic search. Its embedding models are widely used for semantic search and RAG pipelines.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Pinecone is a type of database specifically designed for?",
        "option_a": "Storing relational financial transaction data",
        "option_b": "Storing and searching AI vector embeddings",
        "option_c": "Caching AI model responses for faster replies",
        "option_d": "Real-time event streaming from IoT devices",
        "correct": "b",
        "explanation": "Pinecone is a managed vector database that stores high-dimensional embeddings and enables fast similarity search — a core component in RAG systems and semantic search.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Copy.ai is an AI tool primarily built for?",
        "option_a": "Duplicating and version-controlling code repositories",
        "option_b": "Generating marketing copy, emails, and sales content",
        "option_c": "Copying and organising design assets",
        "option_d": "AI-assisted legal document drafting",
        "correct": "b",
        "explanation": "Copy.ai is an AI writing platform designed for marketing and sales teams to quickly generate ad copy, product descriptions, cold emails, and blog content.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Google's AI assistant embedded in Gmail, Docs, and Sheets is called?",
        "option_a": "Bard for Business",
        "option_b": "Assistant Workspace",
        "option_c": "Duet AI",
        "option_d": "Gemini for Google Workspace",
        "correct": "d",
        "explanation": "Gemini for Google Workspace is Google's AI assistant integrated into Gmail (draft emails), Docs (write/summarise), Sheets (analyse data), and Meet (take notes).",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Pika is an AI tool used for?",
        "option_a": "Generating podcast audio from text prompts",
        "option_b": "AI-powered video generation from text or images",
        "option_c": "Creating AI avatars for video presentations",
        "option_d": "Transcribing and summarising meeting recordings",
        "correct": "b",
        "explanation": "Pika is an AI video generation platform that creates short videos from text prompts or still images, competing in the text-to-video space alongside Runway and Sora.",
        "category": "video-generation",
        "stage": 2,
    },
    {
        "question": "What is 'Constitutional AI' — Anthropic's technique for training Claude?",
        "option_a": "Training AI using only government-approved datasets",
        "option_b": "A method where AI critiques its own outputs against a set of principles",
        "option_c": "Restricting AI to answer only legal and compliance questions",
        "option_d": "Training AI exclusively on constitutional law documents",
        "correct": "b",
        "explanation": "Constitutional AI is Anthropic's technique where Claude is trained to critique and revise its own responses against a set of safety principles, reducing reliance on extensive human feedback.",
        "category": "text-generation",
        "stage": 2,
    },
    {
        "question": "Azure OpenAI Service is best described as?",
        "option_a": "Microsoft's in-house AI model competing with GPT-4",
        "option_b": "A Microsoft Azure service providing enterprise-grade access to OpenAI models",
        "option_c": "An AI tool for automating Azure cloud infrastructure management",
        "option_d": "Microsoft's AI-powered code review platform",
        "correct": "b",
        "explanation": "Azure OpenAI Service gives enterprises access to OpenAI's models (GPT-4, DALL-E, Whisper) through Microsoft Azure's infrastructure — with enterprise security, compliance, and SLA guarantees not available via the standard OpenAI API.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Google Vertex AI is best described as?",
        "option_a": "Google's consumer AI chatbot platform",
        "option_b": "Google's open-source AI model library",
        "option_c": "Google Cloud's managed platform for building, training, and deploying ML models",
        "option_d": "An AI-powered monitoring tool for Google Cloud infrastructure",
        "correct": "c",
        "explanation": "Vertex AI is Google Cloud's unified ML platform for building, training, deploying, and monitoring AI models — including access to Gemini foundation models and Google's full model garden.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "OpenAI's 'Custom GPTs' feature allows users to?",
        "option_a": "Train a completely new GPT model from scratch on their own data",
        "option_b": "Build and share tailored AI assistants with custom instructions, knowledge, and tools",
        "option_c": "Access GPT-4 at a discounted price through customised billing plans",
        "option_d": "Directly modify the underlying GPT-4 model weights",
        "correct": "b",
        "explanation": "Custom GPTs let anyone build specialised AI assistants within ChatGPT — adding custom instructions, uploading knowledge files, and connecting external APIs — without writing any code.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Groq is known in the AI industry for?",
        "option_a": "Providing the largest cloud GPU cluster for model training",
        "option_b": "Building open-source AI models for enterprise use",
        "option_c": "Ultra-fast AI inference using its custom LPU (Language Processing Unit) chips",
        "option_d": "Developing the Grok conversational AI model",
        "correct": "c",
        "explanation": "Groq's LPU hardware delivers exceptionally fast inference speeds for LLMs — often 10× faster than GPU-based alternatives — making it popular for applications requiring very low-latency AI responses.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Scale AI is a company primarily known for providing?",
        "option_a": "Cloud-based AI model hosting services",
        "option_b": "High-quality data labelling and annotation for training AI models",
        "option_c": "AI-powered business intelligence dashboards",
        "option_d": "Open-source AI evaluation benchmarks",
        "correct": "b",
        "explanation": "Scale AI provides human-in-the-loop data labelling, RLHF feedback collection, and AI evaluation services — its data work underpins training of models from OpenAI, Meta, and other major AI labs.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "DeepSeek is notable in the AI landscape because?",
        "option_a": "It is the world's fastest AI hardware manufacturer",
        "option_b": "It created the first AI to pass the Turing Test",
        "option_c": "Its open-source models rival frontier models at a fraction of the training cost",
        "option_d": "It developed the first multilingual real-time translation AI",
        "correct": "c",
        "explanation": "DeepSeek, a Chinese AI lab, released open-source models (DeepSeek-V3, R1) that matched GPT-4 level performance at dramatically lower training costs — challenging assumptions about AI development economics.",
        "category": "text-generation",
        "stage": 2,
    },
    {
        "question": "In AI, 'grounding' refers to?",
        "option_a": "The process of training an AI model on domain-specific data",
        "option_b": "Restricting an AI to only answer questions within a predefined topic",
        "option_c": "Connecting AI responses to specific, verifiable data sources to reduce hallucinations",
        "option_d": "Testing AI systems in a controlled sandbox environment before deployment",
        "correct": "c",
        "explanation": "Grounding anchors AI responses to retrieved documents or live data sources — a technique used in RAG systems to ensure the AI's answers are based on actual verified data rather than potentially incorrect training memories.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "In AI API pricing, a 'token' roughly corresponds to?",
        "option_a": "One complete sentence in the AI's response",
        "option_b": "One API request made to the AI service",
        "option_c": "Approximately 3–4 characters or 0.75 words of text",
        "option_d": "One second of AI processing time",
        "correct": "c",
        "explanation": "AI models process text as tokens — roughly 3–4 characters each. A 1,000-word document is approximately 1,333 tokens. Understanding token consumption is essential for estimating and managing AI API costs.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "'Semantic search' differs from traditional keyword search because it?",
        "option_a": "Searches only within specific file formats like PDF and Word documents",
        "option_b": "Uses AI to understand the meaning and intent behind a query, not just matching words",
        "option_c": "Searches the internet in real time rather than a static index",
        "option_d": "Requires users to write queries in a formal structured language",
        "correct": "b",
        "explanation": "Semantic search uses vector embeddings to find content that is conceptually similar to your query — even if the exact words differ — enabling more natural, meaning-based search across large document collections.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Microsoft Copilot Studio enables organisations to?",
        "option_a": "Monitor and audit Microsoft Copilot usage across the organisation",
        "option_b": "Build custom AI copilots and chatbots for internal or customer-facing use",
        "option_c": "Access additional Microsoft 365 Copilot features for enterprise users",
        "option_d": "Design custom UI themes for the Microsoft Copilot interface",
        "correct": "b",
        "explanation": "Copilot Studio (formerly Power Virtual Agents) lets teams build custom AI assistants using a low-code interface — connecting to internal data, SharePoint, and business systems without heavy development work.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Harvey AI is an AI platform specifically built for?",
        "option_a": "Medical diagnosis and clinical decision support",
        "option_b": "AI-powered legal research, contract analysis, and document drafting",
        "option_c": "Financial modelling and investment portfolio analysis",
        "option_d": "AI-assisted architectural and engineering design",
        "correct": "b",
        "explanation": "Harvey is an AI platform designed for law firms and legal teams — it performs legal research, drafts contracts, analyses documents, and answers legal queries grounded in case law and legislation.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "GitHub Models allows developers to?",
        "option_a": "Store and version-control AI model files within GitHub repositories",
        "option_b": "Explore, test, and access multiple AI models directly from GitHub",
        "option_c": "Automatically generate README documentation files using AI",
        "option_d": "Deploy AI models to GitHub Pages for public API access",
        "correct": "b",
        "explanation": "GitHub Models lets developers test and compare AI models (including GPT-4o, Llama 3, Mistral) in a playground directly within GitHub — and access them via API using their existing GitHub token.",
        "category": "coding",
        "stage": 2,
    },
    {
        "question": "Mistral AI's 'Mixtral' architecture is notable because it uses?",
        "option_a": "A revolutionary attention mechanism that doubles inference speed",
        "option_b": "Mixture of Experts (MoE) — activating only a subset of model parameters per token",
        "option_c": "A hybrid of transformer and recurrent neural network layers",
        "option_d": "Proprietary hardware acceleration chips co-designed with NVIDIA",
        "correct": "b",
        "explanation": "Mixtral 8x7B uses Mixture of Experts, routing each token through only 2 of 8 expert networks — delivering performance close to much larger models while using far less compute per inference.",
        "category": "text-generation",
        "stage": 2,
    },
    {
        "question": "In enterprise AI deployments, 'model fine-tuning' is chosen over prompting when?",
        "option_a": "The task is too simple and prompting would waste tokens",
        "option_b": "The organisation needs consistent style, tone, or domain expertise baked into the model",
        "option_c": "Fine-tuning always produces better results than prompting in every scenario",
        "option_d": "The AI model needs to access real-time internet data",
        "correct": "b",
        "explanation": "Fine-tuning embeds domain knowledge directly into a model through continued training — useful when you need consistent proprietary terminology, specific output formats, or highly specialised task performance at scale.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "What distinguishes Claude's large context window (up to 200,000 tokens)?",
        "option_a": "It allows Claude to respond faster than all other LLMs",
        "option_b": "It enables Claude to process entire books, codebases, or long documents in one prompt",
        "option_c": "It gives Claude access to real-time internet information",
        "option_d": "It allows Claude to remember all past conversations indefinitely",
        "correct": "b",
        "explanation": "Claude's 200K token context window means it can process roughly 500 pages of text in a single interaction — useful for analysing long contracts, large codebases, or extensive research documents without losing context.",
        "category": "text-generation",
        "stage": 2,
    },
    {
        "question": "Salesforce Einstein AI is embedded within which platform?",
        "option_a": "Microsoft Dynamics CRM",
        "option_b": "HubSpot CRM",
        "option_c": "Salesforce CRM and platform",
        "option_d": "SAP SuccessFactors",
        "correct": "c",
        "explanation": "Salesforce Einstein is AI built into the Salesforce platform — providing predictive lead scoring, automated email generation, and AI-powered analytics across Sales Cloud, Service Cloud, and Marketing Cloud.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "OpenAI's GPT-4o Realtime API enables developers to build?",
        "option_a": "Instant text-to-image generation with zero latency",
        "option_b": "Low-latency, streaming voice conversations with GPT-4o",
        "option_c": "Real-time access to live internet search results",
        "option_d": "Zero-latency natural language to database query generation",
        "correct": "b",
        "explanation": "The GPT-4o Realtime API supports streaming speech-in/speech-out conversations with human-like response timing — enabling natural voice assistants without the round-trip latency of older TTS + LLM pipelines.",
        "category": "voice-audio",
        "stage": 2,
    },
    {
        "question": "Stability AI's SDXL model improved on earlier Stable Diffusion versions by?",
        "option_a": "Switching from diffusion to a GAN-based architecture",
        "option_b": "Becoming exclusively cloud-based and no longer open-source",
        "option_c": "Generating higher-resolution images with better detail and prompt adherence",
        "option_d": "Adding real-time video generation alongside image generation",
        "correct": "c",
        "explanation": "SDXL (Stable Diffusion XL) produces significantly higher-resolution, more detailed images than SD 1.5 and 2.x — with improved photorealism and prompt adherence, while remaining open-source for local use.",
        "category": "image-generation",
        "stage": 2,
    },
    {
        "question": "Anthropic's Claude API is made available to developers primarily through?",
        "option_a": "The AWS Marketplace only",
        "option_b": "Anthropic's own API platform and cloud providers like AWS Bedrock and Google Vertex AI",
        "option_c": "Exclusive access through the Claude.ai consumer subscription",
        "option_d": "A GitHub partnership where API access is bundled into Copilot licences",
        "correct": "b",
        "explanation": "Developers access Claude via Anthropic's direct API (api.anthropic.com) as well as through AWS Bedrock and Google Cloud Vertex AI — giving teams flexibility to integrate Claude within their preferred cloud environment.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Google's Imagen model family is focused on?",
        "option_a": "Processing and answering questions about uploaded images",
        "option_b": "High-quality text-to-image generation and image editing",
        "option_c": "Automatically tagging and organising photo libraries",
        "option_d": "Real-time image recognition powering Google Lens",
        "correct": "b",
        "explanation": "Google Imagen is a family of text-to-image diffusion models known for photorealism and strong prompt adherence — available in Vertex AI and powering image creation features across Google Workspace.",
        "category": "image-generation",
        "stage": 2,
    },

    # ── Stage 3: Advanced ──────────────────────────────────────────────────────

    {
        "question": "LangChain is a framework primarily used for?",
        "option_a": "Training custom vision models",
        "option_b": "Deploying AI models on edge devices",
        "option_c": "Building applications powered by large language models",
        "option_d": "Managing cloud GPU clusters",
        "correct": "c",
        "explanation": "LangChain is an open-source framework that simplifies building LLM-powered applications by providing tools for prompt chaining, data integration, and AI agent creation.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Stable Diffusion is best described as?",
        "option_a": "A proprietary text-to-image model by Adobe",
        "option_b": "An open-source text-to-image generation model",
        "option_c": "Google's image generation API",
        "option_d": "An image upscaling tool by NVIDIA",
        "correct": "b",
        "explanation": "Stable Diffusion is an open-source image generation model by Stability AI. Being open-source, it can run locally and has spawned thousands of fine-tuned community variants.",
        "category": "image-generation",
        "stage": 3,
    },
    {
        "question": "AutoGen is a multi-agent AI framework developed by?",
        "option_a": "OpenAI",
        "option_b": "Microsoft Research",
        "option_c": "Google DeepMind",
        "option_d": "Hugging Face",
        "correct": "b",
        "explanation": "AutoGen is an open-source framework from Microsoft Research that enables building multi-agent AI systems where multiple agents collaborate to solve complex tasks.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Adobe Firefly is Adobe's AI tool focused on?",
        "option_a": "AI code review and debugging",
        "option_b": "Predictive analytics for marketing",
        "option_c": "Generative AI for creative content — images, text effects, and video",
        "option_d": "Real-time document translation",
        "correct": "c",
        "explanation": "Adobe Firefly is integrated into Photoshop, Illustrator, and Premiere Pro, letting creators generate images, apply generative fills, and create text effects using AI.",
        "category": "image-generation",
        "stage": 3,
    },
    {
        "question": "Which company created the Mistral family of open-source language models?",
        "option_a": "Meta",
        "option_b": "Mistral AI — a French AI startup",
        "option_c": "Amazon AWS",
        "option_d": "Cohere",
        "correct": "b",
        "explanation": "Mistral AI is a French startup founded in 2023 that has released efficient open-source models including Mistral 7B and Mixtral 8x7B.",
        "category": "text-generation",
        "stage": 3,
    },
    {
        "question": "Tabnine is an AI tool specifically designed for?",
        "option_a": "Generating marketing emails",
        "option_b": "Code completion across multiple IDEs",
        "option_c": "AI-assisted design prototyping",
        "option_d": "Database query optimization",
        "correct": "b",
        "explanation": "Tabnine is an AI code completion tool that integrates with VS Code, JetBrains, and other IDEs, offering both cloud and local model options for privacy-conscious teams.",
        "category": "coding",
        "stage": 3,
    },
    {
        "question": "CrewAI is an open-source framework for?",
        "option_a": "Monitoring AI model performance in production",
        "option_b": "Orchestrating teams of AI agents with defined roles and goals",
        "option_c": "Fine-tuning LLMs on custom enterprise datasets",
        "option_d": "Generating AI avatars for customer service",
        "correct": "b",
        "explanation": "CrewAI lets you build multi-agent systems by defining agents with specific roles, goals, and tools — they collaborate like a team to complete complex tasks autonomously.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "What does RAG stand for in AI development?",
        "option_a": "Recursive Agent Generation",
        "option_b": "Retrieval-Augmented Generation",
        "option_c": "Reinforced Auto-Grading",
        "option_d": "Real-time Adaptive Generation",
        "correct": "b",
        "explanation": "RAG (Retrieval-Augmented Generation) combines a retrieval system (searching a knowledge base) with an LLM to generate answers grounded in specific documents rather than training data alone.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Ollama is a tool that allows you to?",
        "option_a": "Deploy AI models on AWS cloud infrastructure",
        "option_b": "Run large language models locally on your own computer",
        "option_c": "Fine-tune AI models on proprietary datasets",
        "option_d": "Monitor AI model usage across an enterprise",
        "correct": "b",
        "explanation": "Ollama lets you download and run open-source LLMs like LLaMA 3, Mistral, and Gemma locally on your machine with a simple command-line interface — no cloud required.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "LlamaIndex is a framework primarily used for?",
        "option_a": "Indexing and ranking AI chatbot responses by quality",
        "option_b": "Connecting LLMs to external data sources and knowledge bases",
        "option_c": "Benchmarking language model performance against competitors",
        "option_d": "Managing GPU resources during model training",
        "correct": "b",
        "explanation": "LlamaIndex provides data connectors and indexing tools for building RAG pipelines — ingesting documents, chunking, embedding, and querying them with an LLM.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "What does 'fine-tuning' an AI model involve?",
        "option_a": "Improving the model's hardware performance",
        "option_b": "Further training a pre-trained model on domain-specific data",
        "option_c": "Compressing a model to run faster on mobile devices",
        "option_d": "Adjusting the user interface of an AI chatbot",
        "correct": "b",
        "explanation": "Fine-tuning takes a pre-trained foundation model and continues training it on a smaller, task-specific dataset, adapting it to perform better in a particular domain or style.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "Microsoft's open-source Semantic Kernel SDK is designed for?",
        "option_a": "Generating semantically accurate image captions",
        "option_b": "Building AI-powered applications by orchestrating LLMs and plugins",
        "option_c": "Keyword extraction from large document collections",
        "option_d": "Semantic versioning of AI model releases",
        "correct": "b",
        "explanation": "Semantic Kernel is Microsoft's open-source SDK for integrating LLMs into applications using plugins, planners, and memory — used in enterprise AI development with .NET, Python, and Java.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "n8n is best described as?",
        "option_a": "A neural network with 8 hidden layers",
        "option_b": "An open-source, self-hostable workflow automation tool with AI integrations",
        "option_c": "A proprietary no-code app builder with AI features",
        "option_d": "An AI tool for automating network infrastructure management",
        "correct": "b",
        "explanation": "n8n is an open-source workflow automation platform with native AI nodes (LangChain, OpenAI, vector stores) for building agentic pipelines — self-hostable, competing with Zapier.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "In AI, 'quantization' refers to?",
        "option_a": "Measuring the number of parameters in a model",
        "option_b": "Reducing model size by lowering numerical precision to run on less hardware",
        "option_c": "Splitting a large model across multiple GPUs",
        "option_d": "Counting the number of training tokens in a dataset",
        "correct": "b",
        "explanation": "Quantization compresses AI models by reducing weight precision (e.g. from 32-bit to 4-bit), dramatically shrinking model size so they can run on consumer GPUs or laptops.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "The OpenAI Assistants API is primarily used for?",
        "option_a": "Building voice-only AI assistants for smart speakers",
        "option_b": "Building stateful AI agents with tools like code execution and file search",
        "option_c": "Generating training data for custom AI models",
        "option_d": "Evaluating the safety and accuracy of AI model outputs",
        "correct": "b",
        "explanation": "The Assistants API lets developers build AI agents that maintain conversation threads, execute code, search files, and call custom functions — enabling complex, stateful agentic workflows.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "The Model Context Protocol (MCP) is?",
        "option_a": "A standard for measuring the maximum context window of LLMs",
        "option_b": "An open protocol for connecting AI models to external tools and data sources",
        "option_c": "A method for compressing model context to reduce API costs",
        "option_d": "A security standard for enterprise AI deployments",
        "correct": "b",
        "explanation": "MCP (Model Context Protocol) is an open standard developed by Anthropic that defines how AI models connect to external data sources, tools, and services — enabling any LLM to use a consistent interface for tool integration.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "LoRA (Low-Rank Adaptation) is a fine-tuning technique that?",
        "option_a": "Reduces model size by permanently removing unused parameters",
        "option_b": "Fine-tunes only a small set of additional parameters without modifying original weights",
        "option_c": "Adapts a model to run on lower-rank hardware like mobile edge devices",
        "option_d": "Converts model weights from 32-bit to lower precision formats",
        "correct": "b",
        "explanation": "LoRA inserts small trainable matrices into the model while freezing original weights — dramatically reducing the compute and memory needed for fine-tuning while achieving results close to full fine-tuning.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "RLHF (Reinforcement Learning from Human Feedback) is used to?",
        "option_a": "Speed up model training by distributing it across human computing resources",
        "option_b": "Collect human-generated text data for initial model pretraining",
        "option_c": "Align AI model outputs with human preferences through reward modelling",
        "option_d": "Allow non-technical humans to train AI models without expertise",
        "correct": "c",
        "explanation": "RLHF trains a reward model on human preference data, then uses reinforcement learning to optimise the LLM to produce outputs humans prefer — the key alignment technique behind ChatGPT's conversational behaviour.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "In LLM development, 'function calling' (tool use) enables an AI to?",
        "option_a": "Execute Python code directly within the language model's neural network",
        "option_b": "Call predefined external functions or APIs based on user intent, structured as JSON",
        "option_c": "Switch between different AI models mid-conversation based on task complexity",
        "option_d": "Automatically generate and unit-test code functions during inference",
        "correct": "b",
        "explanation": "Function calling allows LLMs to output structured JSON specifying which external function to call and with what arguments — enabling AI to trigger API calls, database queries, and tool integrations in agentic workflows.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Vector embeddings in AI are?",
        "option_a": "Videos compressed using AI to reduce file size",
        "option_b": "Physical representations of AI model weights stored on GPU memory",
        "option_c": "Numerical representations of text or images that capture semantic meaning",
        "option_d": "Binary encodings used to encrypt AI model outputs for security",
        "correct": "c",
        "explanation": "Vector embeddings convert text (or images) into high-dimensional numerical arrays where semantically similar content is mathematically close — the foundation of semantic search, RAG pipelines, and recommendation systems.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "DSPy is a framework for?",
        "option_a": "Deploying AI models on distributed server infrastructure",
        "option_b": "Programmatically optimising LLM prompts and pipelines using examples",
        "option_c": "Data science pipeline orchestration with Python workflows",
        "option_d": "Dynamic speech-to-text processing with real-time AI models",
        "correct": "b",
        "explanation": "DSPy (Declarative Self-improving Python) by Stanford replaces manual prompt engineering with a programming model — you define what you want, and DSPy automatically optimises prompts and few-shot examples to achieve it.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Flowise and LangFlow are tools that allow developers to?",
        "option_a": "Monitor and visualise LLM token usage and API costs",
        "option_b": "Visually build LLM application pipelines using a drag-and-drop interface",
        "option_c": "Convert flowcharts and diagrams into working application code using AI",
        "option_d": "Deploy large language models as containerised microservices",
        "correct": "b",
        "explanation": "Flowise and LangFlow provide visual, no-code/low-code interfaces for building LangChain-based AI pipelines — connecting LLMs, vector stores, and tools by dragging and linking components on a canvas.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "vLLM is a tool used for?",
        "option_a": "Training very large language models on distributed GPU clusters",
        "option_b": "Converting video content into text using language models",
        "option_c": "High-throughput and memory-efficient LLM inference serving",
        "option_d": "Evaluating the safety and accuracy of LLM outputs in production",
        "correct": "c",
        "explanation": "vLLM uses PagedAttention to dramatically improve GPU memory efficiency during inference — enabling much higher request throughput and lower latency when serving LLMs in production, widely used with Llama and Mistral models.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "GGUF is a file format used for?",
        "option_a": "Storing and transferring large AI training datasets efficiently",
        "option_b": "Running quantized LLMs locally with tools like Ollama and llama.cpp",
        "option_c": "Generating user interfaces from AI-written code specifications",
        "option_d": "Archiving and versioning AI experiment results across teams",
        "correct": "b",
        "explanation": "GGUF (GPT-Generated Unified Format) is the file format used by llama.cpp and Ollama for storing quantized LLM weights — enabling efficient local inference of large models on consumer hardware.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "In prompt engineering, 'chain-of-thought' prompting works by?",
        "option_a": "Linking multiple AI models together in a sequential processing chain",
        "option_b": "Asking the AI to reason step-by-step before giving a final answer",
        "option_c": "Chaining multiple prompts to build up a long conversation history",
        "option_d": "Connecting expert quotes to provide authoritative context for AI responses",
        "correct": "b",
        "explanation": "Chain-of-thought prompting (e.g. 'Think step by step') encourages the LLM to show intermediate reasoning steps — significantly improving accuracy on complex reasoning, mathematics, and multi-step problems.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Guardrails AI is a library used for?",
        "option_a": "Adding authentication and access control to AI API endpoints",
        "option_b": "Validating and correcting LLM outputs to ensure they meet structure and safety requirements",
        "option_c": "Building physical safety monitoring systems for AI data centres",
        "option_d": "Monitoring AI model inference costs and alerting on budget overruns",
        "correct": "b",
        "explanation": "Guardrails AI defines validators that check LLM outputs (JSON schema compliance, content safety, PII detection) and can automatically re-prompt the model to fix invalid outputs — critical for production AI reliability.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "In multi-agent AI systems, an 'orchestrator agent' is responsible for?",
        "option_a": "Deploying and auto-scaling AI agents on cloud infrastructure",
        "option_b": "Monitoring other agents for safety violations and policy compliance",
        "option_c": "Coordinating and directing specialised agents to complete a complex task",
        "option_d": "Providing shared memory and context storage for all agents in the system",
        "correct": "c",
        "explanation": "An orchestrator agent acts as the 'manager' in multi-agent workflows — it breaks down tasks, assigns them to specialised sub-agents, collects their outputs, and synthesises the final result.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "The key difference between LangChain and LlamaIndex is?",
        "option_a": "LangChain is Python-only; LlamaIndex supports JavaScript as well",
        "option_b": "LangChain focuses on agent and chain orchestration; LlamaIndex specialises in data ingestion and RAG",
        "option_c": "LangChain is open-source; LlamaIndex requires a paid enterprise licence",
        "option_d": "LangChain is for production use only; LlamaIndex is for prototyping only",
        "correct": "b",
        "explanation": "LangChain excels at chaining LLM calls, tool use, and multi-agent workflows. LlamaIndex is purpose-built for data ingestion, chunking, indexing, and retrieval — making it the first choice for RAG pipeline construction.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "'Prompt injection' is a security vulnerability where?",
        "option_a": "AI systems are overwhelmed with too many requests causing service failures",
        "option_b": "Malicious instructions hidden in user input override the AI's system prompt",
        "option_c": "Sensitive data is accidentally included in AI training datasets",
        "option_d": "AI model weights are corrupted through adversarial hardware attacks",
        "correct": "b",
        "explanation": "Prompt injection attacks embed instructions in user-supplied content (e.g. a document the AI reads) that hijack the AI agent's behaviour — a critical security concern for autonomous AI agents that process untrusted data.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Phidata is a framework for building?",
        "option_a": "Physics-based simulation environments for AI robotics training",
        "option_b": "AI agents with built-in memory, knowledge bases, and tool integrations",
        "option_c": "Fine-tuning pipelines for Microsoft's Phi small language models",
        "option_d": "Data validation pipelines for AI training dataset quality control",
        "correct": "b",
        "explanation": "Phidata is a Python framework for building AI agents and agent teams — providing structured workflows, built-in memory (conversation and vector), and tool integration (web search, databases, APIs) with minimal boilerplate.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "The 'self-attention mechanism' in transformer models is significant because it?",
        "option_a": "Processes sentence tokens strictly left-to-right for faster training",
        "option_b": "Allows the model to weigh the relevance of every token to every other token simultaneously",
        "option_c": "Compresses input text to reduce the token count before processing",
        "option_d": "Routes different parts of the input to different GPU layers automatically",
        "correct": "b",
        "explanation": "Self-attention (introduced in the 2017 'Attention Is All You Need' paper) lets transformers capture long-range dependencies by relating all tokens to each other in parallel — overcoming the sequential limitations of RNNs and forming the foundation of every modern LLM.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "Knowledge distillation in AI is a technique used to?",
        "option_a": "Extract and summarise key facts from an AI model's training dataset",
        "option_b": "Transfer knowledge from a large 'teacher' model into a smaller 'student' model",
        "option_c": "Merge multiple fine-tuned model versions into one consolidated model",
        "option_d": "Remove redundant training examples to reduce dataset size before training",
        "correct": "b",
        "explanation": "Knowledge distillation trains a compact 'student' model to mimic the output distributions of a larger 'teacher' model — producing a smaller, faster model that retains much of the teacher's performance at a fraction of the inference cost.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "DPO (Direct Preference Optimization) is an alignment technique that?",
        "option_a": "Optimises responses by directly accepting high-quality examples from annotators",
        "option_b": "Replaces the separate reward model in RLHF by training the LLM directly on preference data",
        "option_c": "Dynamically adjusts model parameters based on real-time user preference signals",
        "option_d": "Optimises prompt templates to improve response quality without retraining the model",
        "correct": "b",
        "explanation": "DPO simplifies RLHF by eliminating the separate reward model — it trains the LLM directly on chosen vs. rejected response pairs using a contrastive loss, achieving comparable alignment with significantly less complexity.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "MMLU (Massive Multitask Language Understanding) is an AI benchmark that tests?",
        "option_a": "A model's throughput speed when processing large prompt batches",
        "option_b": "A model's knowledge across 57 subjects including law, medicine, and mathematics",
        "option_c": "A model's ability to understand and generate text in multiple languages",
        "option_d": "A model's capability to handle long multi-turn conversations without losing context",
        "correct": "b",
        "explanation": "MMLU evaluates LLM knowledge breadth across 57 diverse academic subjects from STEM to humanities to law and medicine — one of the standard benchmarks used to compare frontier model capabilities.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "In AI safety, 'red-teaming' a model refers to?",
        "option_a": "Deploying a backup AI model (the 'red team') when the primary model fails",
        "option_b": "Adversarially probing a model to surface harmful, unsafe, or policy-violating outputs",
        "option_c": "A competitive benchmark where multiple AI models race to complete the same task",
        "option_d": "Using red annotations to mark incorrect model responses during RLHF data collection",
        "correct": "b",
        "explanation": "AI red-teaming involves deliberately trying to elicit unsafe, biased, or harmful responses from a model — simulating real-world misuse to identify weaknesses before deployment. It is a standard safety practice at Anthropic, OpenAI, and other frontier AI labs.",
        "category": "ml-platforms",
        "stage": 3,
    },
]

# Attach IDs and source at module load
for _q in QUESTION_BANK:
    _q["id"]     = _qid(_q["question"])
    _q["source"] = "local"


def get_all_questions() -> list[dict]:
    return list(QUESTION_BANK)


def get_questions_for_stage(
    stage: int,
    n: int = 5,
    date_str: str | None = None,
    exclude_ids: set[str] | None = None,
) -> list[dict]:
    """
    Return n questions for a given stage for a specific date.

    Uses SHA-256 seeding: each (date_str, stage) pair produces a
    cryptographically independent seed — no sequential correlation.

    exclude_ids: question IDs used recently; excluded before shuffling.
    Falls back to full pool if exclusion leaves fewer than n questions.
    """
    if date_str is None:
        date_str = _date.today().isoformat()

    pool = [q for q in QUESTION_BANK if q["stage"] == stage]

    if exclude_ids:
        available = [q for q in pool if q["id"] not in exclude_ids]
        if len(available) >= n:
            pool = available

    seed = _daily_seed(date_str, stage)
    rng  = random.Random(seed)
    rng.shuffle(pool)
    return pool[:n]


def get_questions_for_quiz(n: int = 5, seed: int | None = None) -> list[dict]:
    """Backward-compat shim — kept for any external callers."""
    pool = list(QUESTION_BANK)
    rng  = random.Random(seed)
    rng.shuffle(pool)
    return pool[:n]
