"""
Quiz source — AI tools awareness question bank.
Questions divided into 3 stages by difficulty/progression.
Stage 1: Foundation  — widely-known tools
Stage 2: Applied     — platform and ecosystem knowledge
Stage 3: Advanced    — frameworks, open-source, agents
"""

import hashlib
import random


def _qid(text: str) -> str:
    return hashlib.md5(text.encode()).hexdigest()[:12]


QUESTION_BANK: list[dict] = [

    # ── Stage 1: Foundation ────────────────────────────────────────────────────

    {
        "question": "Which company developed the Claude AI assistant?",
        "option_a": "OpenAI",
        "option_b": "Google",
        "option_c": "Anthropic",
        "option_d": "Meta",
        "correct": "c",
        "explanation": "Claude is developed by Anthropic, an AI safety company founded in 2021 by former OpenAI researchers including Dario and Daniela Amodei.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "GitHub Copilot is primarily used as a tool for?",
        "option_a": "Generating images from text prompts",
        "option_b": "AI-powered code completion and generation",
        "option_c": "Video editing with AI",
        "option_d": "Translating documents automatically",
        "correct": "b",
        "explanation": "GitHub Copilot is an AI pair programmer that suggests code completions and generates entire functions, powered by OpenAI Codex and later GPT-4.",
        "category": "coding",
        "stage": 1,
    },
    {
        "question": "Midjourney is best described as a tool for?",
        "option_a": "AI-generated images from text descriptions",
        "option_b": "Writing long-form articles automatically",
        "option_c": "Transcribing audio to text",
        "option_d": "Automating spreadsheet tasks",
        "correct": "a",
        "explanation": "Midjourney is a generative AI image tool that creates high-quality artwork and photorealistic visuals from natural language text prompts.",
        "category": "image-generation",
        "stage": 1,
    },
    {
        "question": "Which AI tool is best known for web search with real-time cited answers?",
        "option_a": "Claude",
        "option_b": "Perplexity AI",
        "option_c": "Stable Diffusion",
        "option_d": "ElevenLabs",
        "correct": "b",
        "explanation": "Perplexity AI is an AI-powered search engine that delivers direct answers with cited web sources, combining LLM capabilities with real-time search.",
        "category": "ai-search",
        "stage": 1,
    },
    {
        "question": "DALL-E is an AI image generation model created by?",
        "option_a": "Google",
        "option_b": "Stability AI",
        "option_c": "Microsoft",
        "option_d": "OpenAI",
        "correct": "d",
        "explanation": "DALL-E is developed by OpenAI. DALL-E 3 is integrated into ChatGPT and is one of the leading text-to-image generation models.",
        "category": "image-generation",
        "stage": 1,
    },
    {
        "question": "What kind of tool is Cursor?",
        "option_a": "A video generation platform",
        "option_b": "An AI-enhanced code editor",
        "option_c": "A voice cloning tool",
        "option_d": "An email automation assistant",
        "correct": "b",
        "explanation": "Cursor is an AI-first code editor built on VS Code that integrates chat, code generation, and intelligent editing directly into the development environment.",
        "category": "coding",
        "stage": 1,
    },
    {
        "question": "Google's AI assistant was renamed from Bard to which name in February 2024?",
        "option_a": "LaMDA",
        "option_b": "Vertex AI",
        "option_c": "Gemini",
        "option_d": "Duet AI",
        "correct": "c",
        "explanation": "Google renamed its AI assistant from Bard to Gemini in February 2024, aligning it with the underlying Gemini family of multimodal AI models.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "ChatGPT was developed and launched by which company in November 2022?",
        "option_a": "Google",
        "option_b": "Microsoft",
        "option_c": "OpenAI",
        "option_d": "Anthropic",
        "correct": "c",
        "explanation": "ChatGPT was launched by OpenAI in November 2022 and became the fastest-growing consumer application in history, reaching 100 million users in just two months.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "What does 'AI hallucination' mean?",
        "option_a": "The AI generates visual illusions in images",
        "option_b": "The AI confidently produces false or invented information",
        "option_c": "The AI runs too slowly due to overloading",
        "option_d": "The AI refuses to answer a question",
        "correct": "b",
        "explanation": "AI hallucination refers to when a language model generates plausible-sounding but factually incorrect or invented information — a key limitation to be aware of when using AI tools.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "Canva's suite of AI-powered design features is collectively called?",
        "option_a": "Canva AI+",
        "option_b": "Design Intelligence",
        "option_c": "Magic Studio",
        "option_d": "Smart Canvas",
        "correct": "c",
        "explanation": "Canva's Magic Studio bundles AI tools including Magic Write (text), Magic Media (image/video generation), Magic Eraser, and Magic Edit into one integrated creative suite.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Notion AI is an AI assistant built into which productivity workspace?",
        "option_a": "Microsoft OneNote",
        "option_b": "Notion",
        "option_c": "Confluence",
        "option_d": "Evernote",
        "correct": "b",
        "explanation": "Notion AI is natively integrated into Notion's workspace, helping users write, summarise, translate, and brainstorm without leaving their notes and documents.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "Grammarly uses AI primarily to assist with?",
        "option_a": "Generating code in multiple languages",
        "option_b": "Creating AI-generated images",
        "option_c": "Writing assistance — grammar, clarity, and tone",
        "option_d": "Translating spoken audio in real time",
        "correct": "c",
        "explanation": "Grammarly is an AI writing assistant that checks grammar, improves clarity, adjusts tone, and now includes generative AI features for drafting and rewriting text.",
        "category": "productivity",
        "stage": 1,
    },
    {
        "question": "What makes GPT-4 'multimodal' compared to earlier GPT models?",
        "option_a": "It can run on multiple devices simultaneously",
        "option_b": "It supports multiple programming languages",
        "option_c": "It can process both text and images as input",
        "option_d": "It has multiple response styles to choose from",
        "correct": "c",
        "explanation": "GPT-4's multimodal capability means it accepts images as well as text as input, allowing it to analyse photos, charts, and documents — not just written prompts.",
        "category": "text-generation",
        "stage": 1,
    },
    {
        "question": "OpenAI's Sora model is capable of?",
        "option_a": "Translating speech between 100 languages",
        "option_b": "Generating realistic video from text descriptions",
        "option_c": "Creating 3D models from photos",
        "option_d": "Automating browser tasks with AI agents",
        "correct": "b",
        "explanation": "Sora is OpenAI's text-to-video model that can generate high-quality, realistic videos up to one minute long from a written prompt.",
        "category": "video-generation",
        "stage": 1,
    },
    {
        "question": "What does 'LLM' stand for in AI?",
        "option_a": "Low-Latency Machine",
        "option_b": "Large Language Model",
        "option_c": "Layered Learning Module",
        "option_d": "Linear Logic Matrix",
        "correct": "b",
        "explanation": "LLM stands for Large Language Model — a type of AI trained on vast text data to understand and generate human language. GPT-4, Claude, and Gemini are all LLMs.",
        "category": "text-generation",
        "stage": 1,
    },

    # ── Stage 2: Applied ───────────────────────────────────────────────────────

    {
        "question": "ElevenLabs is primarily known for which AI capability?",
        "option_a": "Generating 3D models from text",
        "option_b": "AI voice synthesis and voice cloning",
        "option_c": "Real-time language translation",
        "option_d": "AI-powered financial forecasting",
        "correct": "b",
        "explanation": "ElevenLabs specializes in AI voice technology — it can clone voices and generate natural-sounding speech in multiple languages.",
        "category": "voice-audio",
        "stage": 2,
    },
    {
        "question": "What is Hugging Face primarily known as in the AI ecosystem?",
        "option_a": "An open-source ML model hub and community platform",
        "option_b": "A cloud GPU rental service",
        "option_c": "An AI hardware manufacturer",
        "option_d": "A proprietary LLM provider",
        "correct": "a",
        "explanation": "Hugging Face is the leading open-source AI platform hosting thousands of models, datasets, and demo Spaces, and maintains the widely used Transformers library.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "OpenAI's Whisper model is specialized for which task?",
        "option_a": "Speech recognition and audio transcription",
        "option_b": "Image generation from text",
        "option_c": "Music composition",
        "option_d": "Video subtitle generation",
        "correct": "a",
        "explanation": "Whisper is OpenAI's open-source automatic speech recognition system that transcribes and translates audio in dozens of languages with high accuracy.",
        "category": "voice-audio",
        "stage": 2,
    },
    {
        "question": "What is Meta's flagship open-source large language model family called?",
        "option_a": "Falcon",
        "option_b": "LLaMA",
        "option_c": "Mixtral",
        "option_d": "Phi",
        "correct": "b",
        "explanation": "LLaMA (Large Language Model Meta AI) is Meta's family of open-source foundation models. LLaMA 3 is widely used for research, fine-tuning, and local deployment.",
        "category": "text-generation",
        "stage": 2,
    },
    {
        "question": "Microsoft Copilot is deeply integrated into which platform?",
        "option_a": "Google Workspace",
        "option_b": "Salesforce CRM",
        "option_c": "Microsoft 365 (Word, Excel, Teams, Outlook)",
        "option_d": "Adobe Creative Cloud",
        "correct": "c",
        "explanation": "Microsoft Copilot is embedded across Microsoft 365 apps helping users draft documents, analyze data in Excel, summarise Teams meetings, and compose emails in Outlook.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Runway is an AI tool primarily used for?",
        "option_a": "Writing marketing copy",
        "option_b": "AI video generation and editing",
        "option_c": "Generating 3D architectural designs",
        "option_d": "Automating customer support",
        "correct": "b",
        "explanation": "Runway is an AI creative suite known for its Gen-2 and Gen-3 text-to-video models, widely used by filmmakers and creators for AI-assisted video production.",
        "category": "video-generation",
        "stage": 2,
    },
    {
        "question": "NotebookLM, developed by Google, is best used for?",
        "option_a": "Writing code using AI",
        "option_b": "Chatting with and summarising your own documents",
        "option_c": "Generating realistic human faces",
        "option_d": "Automating social media posts",
        "correct": "b",
        "explanation": "NotebookLM lets you upload your own documents and ask questions grounded in them, generating summaries and insights from your specific sources.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Amazon Bedrock is best described as?",
        "option_a": "Amazon's in-house AI assistant for shopping",
        "option_b": "A managed AWS service for accessing multiple foundation models via API",
        "option_c": "A cloud GPU cluster for training custom AI models",
        "option_d": "Amazon's AI-powered logistics optimisation platform",
        "correct": "b",
        "explanation": "Amazon Bedrock is a fully managed AWS service providing access to foundation models from Anthropic (Claude), Meta, Mistral, and others through a single API without managing infrastructure.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Jasper AI is primarily used by businesses for?",
        "option_a": "Automating software testing",
        "option_b": "AI-generated marketing and sales content",
        "option_c": "Real-time financial data analysis",
        "option_d": "Managing cloud infrastructure costs",
        "correct": "b",
        "explanation": "Jasper is an AI content platform built for marketing teams, helping generate blog posts, ad copy, social media content, and brand-aligned text at scale.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Cohere is an AI company focused primarily on?",
        "option_a": "Consumer chatbot applications",
        "option_b": "AI-powered video and image editing",
        "option_c": "Enterprise NLP — embeddings, text generation, and search APIs",
        "option_d": "Autonomous vehicle AI systems",
        "correct": "c",
        "explanation": "Cohere provides enterprise-grade NLP APIs for text generation, classification, and semantic search. Its embedding models are widely used for semantic search and RAG pipelines.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Pinecone is a type of database specifically designed for?",
        "option_a": "Storing relational financial transaction data",
        "option_b": "Storing and searching AI vector embeddings",
        "option_c": "Caching AI model responses for faster replies",
        "option_d": "Real-time event streaming from IoT devices",
        "correct": "b",
        "explanation": "Pinecone is a managed vector database that stores high-dimensional embeddings and enables fast similarity search — a core component in RAG systems and semantic search.",
        "category": "ml-platforms",
        "stage": 2,
    },
    {
        "question": "Copy.ai is an AI tool primarily built for?",
        "option_a": "Duplicating and version-controlling code repositories",
        "option_b": "Generating marketing copy, emails, and sales content",
        "option_c": "Copying and organising design assets",
        "option_d": "AI-assisted legal document drafting",
        "correct": "b",
        "explanation": "Copy.ai is an AI writing platform designed for marketing and sales teams to quickly generate ad copy, product descriptions, cold emails, and blog content.",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Google's AI assistant embedded in Gmail, Docs, and Sheets is called?",
        "option_a": "Bard for Business",
        "option_b": "Assistant Workspace",
        "option_c": "Duet AI",
        "option_d": "Gemini for Google Workspace",
        "correct": "d",
        "explanation": "Gemini for Google Workspace is Google's AI assistant integrated into Gmail (draft emails), Docs (write/summarise), Sheets (analyse data), and Meet (take notes).",
        "category": "productivity",
        "stage": 2,
    },
    {
        "question": "Pika is an AI tool used for?",
        "option_a": "Generating podcast audio from text prompts",
        "option_b": "AI-powered video generation from text or images",
        "option_c": "Creating AI avatars for video presentations",
        "option_d": "Transcribing and summarising meeting recordings",
        "correct": "b",
        "explanation": "Pika is an AI video generation platform that creates short videos from text prompts or still images, competing in the text-to-video space alongside Runway and Sora.",
        "category": "video-generation",
        "stage": 2,
    },
    {
        "question": "What is 'Constitutional AI' — Anthropic's technique for training Claude?",
        "option_a": "Training AI using only government-approved datasets",
        "option_b": "A method where AI critiques its own outputs against a set of principles",
        "option_c": "Restricting AI to answer only legal and compliance questions",
        "option_d": "Training AI exclusively on constitutional law documents",
        "correct": "b",
        "explanation": "Constitutional AI is Anthropic's technique where Claude is trained to critique and revise its own responses against a set of safety principles, reducing reliance on extensive human feedback.",
        "category": "text-generation",
        "stage": 2,
    },

    # ── Stage 3: Advanced ──────────────────────────────────────────────────────

    {
        "question": "LangChain is a framework primarily used for?",
        "option_a": "Training custom vision models",
        "option_b": "Deploying AI models on edge devices",
        "option_c": "Building applications powered by large language models",
        "option_d": "Managing cloud GPU clusters",
        "correct": "c",
        "explanation": "LangChain is an open-source framework that simplifies building LLM-powered applications by providing tools for prompt chaining, data integration, and AI agent creation.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Stable Diffusion is best described as?",
        "option_a": "A proprietary text-to-image model by Adobe",
        "option_b": "An open-source text-to-image generation model",
        "option_c": "Google's image generation API",
        "option_d": "An image upscaling tool by NVIDIA",
        "correct": "b",
        "explanation": "Stable Diffusion is an open-source image generation model by Stability AI. Being open-source, it can run locally and has spawned thousands of fine-tuned community variants.",
        "category": "image-generation",
        "stage": 3,
    },
    {
        "question": "AutoGen is a multi-agent AI framework developed by?",
        "option_a": "OpenAI",
        "option_b": "Microsoft Research",
        "option_c": "Google DeepMind",
        "option_d": "Hugging Face",
        "correct": "b",
        "explanation": "AutoGen is an open-source framework from Microsoft Research that enables building multi-agent AI systems where multiple agents collaborate to solve complex tasks.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Adobe Firefly is Adobe's AI tool focused on?",
        "option_a": "AI code review and debugging",
        "option_b": "Predictive analytics for marketing",
        "option_c": "Generative AI for creative content — images, text effects, and video",
        "option_d": "Real-time document translation",
        "correct": "c",
        "explanation": "Adobe Firefly is integrated into Photoshop, Illustrator, and Premiere Pro, letting creators generate images, apply generative fills, and create text effects using AI.",
        "category": "image-generation",
        "stage": 3,
    },
    {
        "question": "Which company created the Mistral family of open-source language models?",
        "option_a": "Meta",
        "option_b": "Mistral AI — a French AI startup",
        "option_c": "Amazon AWS",
        "option_d": "Cohere",
        "correct": "b",
        "explanation": "Mistral AI is a French startup founded in 2023 that has released efficient open-source models including Mistral 7B and Mixtral 8x7B.",
        "category": "text-generation",
        "stage": 3,
    },
    {
        "question": "Tabnine is an AI tool specifically designed for?",
        "option_a": "Generating marketing emails",
        "option_b": "Code completion across multiple IDEs",
        "option_c": "AI-assisted design prototyping",
        "option_d": "Database query optimization",
        "correct": "b",
        "explanation": "Tabnine is an AI code completion tool that integrates with VS Code, JetBrains, and other IDEs, offering both cloud and local model options for privacy-conscious teams.",
        "category": "coding",
        "stage": 3,
    },
    {
        "question": "CrewAI is an open-source framework for?",
        "option_a": "Monitoring AI model performance in production",
        "option_b": "Orchestrating teams of AI agents with defined roles and goals",
        "option_c": "Fine-tuning LLMs on custom enterprise datasets",
        "option_d": "Generating AI avatars for customer service",
        "correct": "b",
        "explanation": "CrewAI lets you build multi-agent systems by defining agents with specific roles, goals, and tools — they collaborate like a team to complete complex tasks autonomously.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "What does RAG stand for in AI development?",
        "option_a": "Recursive Agent Generation",
        "option_b": "Retrieval-Augmented Generation",
        "option_c": "Reinforced Auto-Grading",
        "option_d": "Real-time Adaptive Generation",
        "correct": "b",
        "explanation": "RAG (Retrieval-Augmented Generation) combines a retrieval system (searching a knowledge base) with an LLM to generate answers grounded in specific documents rather than training data alone.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "Ollama is a tool that allows you to?",
        "option_a": "Deploy AI models on AWS cloud infrastructure",
        "option_b": "Run large language models locally on your own computer",
        "option_c": "Fine-tune AI models on proprietary datasets",
        "option_d": "Monitor AI model usage across an enterprise",
        "correct": "b",
        "explanation": "Ollama lets you download and run open-source LLMs like LLaMA 3, Mistral, and Gemma locally on your machine with a simple command-line interface — no cloud required.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "LlamaIndex is a framework primarily used for?",
        "option_a": "Indexing and ranking AI chatbot responses by quality",
        "option_b": "Connecting LLMs to external data sources and knowledge bases",
        "option_c": "Benchmarking language model performance against competitors",
        "option_d": "Managing GPU resources during model training",
        "correct": "b",
        "explanation": "LlamaIndex provides data connectors and indexing tools for building RAG pipelines — ingesting documents, chunking, embedding, and querying them with an LLM.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "What does 'fine-tuning' an AI model involve?",
        "option_a": "Improving the model's hardware performance",
        "option_b": "Further training a pre-trained model on domain-specific data",
        "option_c": "Compressing a model to run faster on mobile devices",
        "option_d": "Adjusting the user interface of an AI chatbot",
        "correct": "b",
        "explanation": "Fine-tuning takes a pre-trained foundation model and continues training it on a smaller, task-specific dataset, adapting it to perform better in a particular domain or style.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "Microsoft's open-source Semantic Kernel SDK is designed for?",
        "option_a": "Generating semantically accurate image captions",
        "option_b": "Building AI-powered applications by orchestrating LLMs and plugins",
        "option_c": "Keyword extraction from large document collections",
        "option_d": "Semantic versioning of AI model releases",
        "correct": "b",
        "explanation": "Semantic Kernel is Microsoft's open-source SDK for integrating LLMs into applications using plugins, planners, and memory — used in enterprise AI development with .NET, Python, and Java.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "n8n is best described as?",
        "option_a": "A neural network with 8 hidden layers",
        "option_b": "An open-source, self-hostable workflow automation tool with AI integrations",
        "option_c": "A proprietary no-code app builder with AI features",
        "option_d": "An AI tool for automating network infrastructure management",
        "correct": "b",
        "explanation": "n8n is an open-source workflow automation platform with native AI nodes (LangChain, OpenAI, vector stores) for building agentic pipelines — self-hostable, competing with Zapier.",
        "category": "agent-frameworks",
        "stage": 3,
    },
    {
        "question": "In AI, 'quantization' refers to?",
        "option_a": "Measuring the number of parameters in a model",
        "option_b": "Reducing model size by lowering numerical precision to run on less hardware",
        "option_c": "Splitting a large model across multiple GPUs",
        "option_d": "Counting the number of training tokens in a dataset",
        "correct": "b",
        "explanation": "Quantization compresses AI models by reducing weight precision (e.g. from 32-bit to 4-bit), dramatically shrinking model size so they can run on consumer GPUs or laptops.",
        "category": "ml-platforms",
        "stage": 3,
    },
    {
        "question": "The OpenAI Assistants API is primarily used for?",
        "option_a": "Building voice-only AI assistants for smart speakers",
        "option_b": "Building stateful AI agents with tools like code execution and file search",
        "option_c": "Generating training data for custom AI models",
        "option_d": "Evaluating the safety and accuracy of AI model outputs",
        "correct": "b",
        "explanation": "The Assistants API lets developers build AI agents that maintain conversation threads, execute code, search files, and call custom functions — enabling complex, stateful agentic workflows.",
        "category": "agent-frameworks",
        "stage": 3,
    },
]

# Attach IDs and source at module load
for _q in QUESTION_BANK:
    _q["id"]     = _qid(_q["question"])
    _q["source"] = "local"


def get_all_questions() -> list[dict]:
    return list(QUESTION_BANK)


def get_questions_for_stage(stage: int, n: int = 5, seed: int | None = None) -> list[dict]:
    """Return n questions for a given stage, seeded for daily consistency."""
    pool = [q for q in QUESTION_BANK if q["stage"] == stage]
    rng  = random.Random((seed or 0) + stage * 1000)
    rng.shuffle(pool)
    return pool[:n]


def get_questions_for_quiz(n: int = 5, seed: int | None = None) -> list[dict]:
    """Backward-compat shim — kept for any external callers."""
    pool = list(QUESTION_BANK)
    rng  = random.Random(seed)
    rng.shuffle(pool)
    return pool[:n]
